# Generated by Django 5.2.2 on 2025-09-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('login_email', models.EmailField(max_length=254, unique=True, verbose_name='ログインID（メールアドレス）')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'db_table': '管理者',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('parent_category_id', models.PositiveIntegerField(verbose_name='親カテゴリID')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='表示名称（タイトル）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要説明')),
                ('updater_user_id', models.PositiveIntegerField(verbose_name='更新者ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='添付ファイル格納先URL')),
                ('file_type', models.CharField(max_length=50, verbose_name='ファイル種別')),
                ('administrator', models.ForeignKey(db_column='管理者ID', on_delete=django.db.models.deletion.CASCADE, to='share.administrator')),
                ('category', models.ForeignKey(db_column='カテゴリID', on_delete=django.db.models.deletion.CASCADE, to='share.category')),
            ],
            options={
                'verbose_name': 'コンテンツ',
                'verbose_name_plural': 'コンテンツ',
                'db_table': 'コンテンツ',
            },
        ),
    ]
