# Generated by Django 5.2.2 on 2025-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_remove_category_parent_category_id_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.PositiveIntegerField(blank=True, db_column='親カテゴリ', null=True),
        ),
    ]
