# Generated by Django 5.2.2 on 2025-09-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
