# Generated by Django 5.2.2 on 2025-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_alter_category_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, db_column='親カテゴリ', null=True),
        ),
    ]
