# Generated by Django 5.2.2 on 2025-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_alter_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='表示順(カテゴリ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='contents_display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='表示順(コンテンツ)'),
            preserve_default=False,
        ),
    ]
