# Generated by Django 5.2.2 on 2025-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_category_category_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_display_order',
        ),
        migrations.AddField(
            model_name='category',
            name='category_display_order_leftmenues',
            field=models.PositiveIntegerField(default=1, verbose_name='表示順(左メニュー)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_display_order_tabs',
            field=models.PositiveIntegerField(default=1, verbose_name='表示順(タブ)'),
            preserve_default=False,
        ),
    ]
