# Generated by Django 5.2.2 on 2025-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_remove_category_category_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_display_order_leftmenues',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='表示順(左メニュー)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_display_order_tabs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='表示順(タブ)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contents_display_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='表示順(コンテンツ)'),
        ),
    ]
