# Generated by Django 5.2.2 on 2025-11-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_alter_category_category_display_order_leftmenues_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrator',
            table='administrator',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='content',
            table='contents',
        ),
    ]
